
spring.application.name=MANAGEMENT-SERVICE
server.port=${PORT:8086}

services.account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
services.add-pg-service.url=${ADD_PG_SERVICE_URL:http://localhost:8084}
services.inquiry-service.url=${INQUIRY_SERVICE_URL:http://localhost:8083}
services.tenant-service.url=${TENANT_SERVICE_URL:http://localhost:8085}

spring.main.lazy-initialization=true
spring.cloud.compatibility-verifier.enabled=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never