spring.application.name=MANAGEMENT-SERVICE
server.port=${PORT:8086}

# Disable database auto-configuration (we don't need a database)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Feign clients URL configuration
services.account-service.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
services.add-pg-service.url=${ADD_PG_SERVICE_URL:http://localhost:8084}
services.inquiry-service.url=${INQUIRY_SERVICE_URL:http://localhost:8083}
services.tenant-service.url=${TENANT_SERVICE_URL:http://localhost:8085}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never